Puroguramu.App/Pages/Lecons/CreateLesson.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains.modelsDomains;
using Puroguramu.Domains.Repositories;

namespace Puroguramu.App.Pages.Lecons
{
    public class CreateLessonModel : PageModel
    {
        private readonly ILessonRepository _lessonRepository;

        public CreateLessonModel(ILessonRepository lessonRepository)
        {
            _lessonRepository = lessonRepository;
        }

        [BindProperty]
        public LessonDto Lesson { get; set; }


        public string ErrorMessage { get; set; }

        public void OnGet()
        {
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                await _lessonRepository.CreateLessonAsync(Lesson);
                return RedirectToPage("/Dashboard/TeacherDashboard");
            }
            catch (InvalidOperationException ex)
            {
                ErrorMessage = ex.Message;
                return Page();
            }
        }
    }
}

Puroguramu.App/Pages/Lecons/EditLesson.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains.modelsDomains;
using Puroguramu.Domains.Repositories;
using Puroguramu.Infrastructures.Data.models;

namespace Puroguramu.App.Pages.Lecons
{
    public class EditLesson : PageModel
    {
        private readonly ILessonRepository _lessonRepository;
        private readonly IExoRepository _exoRepository;
        private readonly IStudentRepository _studentRepository;

        public List<ExerciseDto> Exercises { get; set; } = new List<ExerciseDto>();

        [BindProperty]
        public LessonEditDto Lesson { get; set; }
        public StudentExerciseDto StudentExercise { get; set; }

        public EditLesson(ILessonRepository lessonRepository, IExoRepository exoRepository, IStudentRepository studentRepository)
        {
            _lessonRepository = lessonRepository;
            _exoRepository = exoRepository;
            _studentRepository = studentRepository;
        }

        public async Task OnGetAsync(Guid id)
        {
            Lesson = await _lessonRepository.GetLessonByIdAsync(id);
            Exercises = await _lessonRepository.GetExercisesByLessonIdAsync(id);
        }


        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Console.WriteLine("OnPostAsync UpdateLessonAsync");
            await _lessonRepository.UpdateLessonAsync(Lesson);
            return RedirectToPage("/Dashboard/TeacherDashboard");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostMoveExerciseAsync(Guid id, string direction, string lessonId)
        {
            Console.WriteLine("Entry OnPostMoveExerciseAsync");
            var moveUp = direction == "up";
            await _exoRepository.MoveExerciseAsync(id, moveUp);
            return RedirectToPage("/Lecons/EditLesson", new { id = lessonId });
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostToggleExerciseAsync(Guid id, string lessonId)
        {
            Console.WriteLine($"Entry OnPostToggleExerciseAsync with id: {id} and lessonId: {lessonId}");
            await _exoRepository.ToggleExerciseAsync(id);
            return RedirectToPage("/Lecons/EditLesson", new { id = lessonId });
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostDeleteExerciseAsync(Guid id, string lessonId)
        {
            await _exoRepository.DeleteExerciseAsync(id);
            return RedirectToPage("/Lecons/EditLesson", new { id = lessonId });
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostResetExerciseAsync(Guid id, Guid lessonId)
        {
            var student = _studentRepository.GetStudentProfileAsync(User);
            Console.WriteLine("id trouvé = " + student.Id);
            await _lessonRepository.DeleteStudentExerciseDataAsync(id, student.Id.ToString());
            await _lessonRepository.ResetExerciseAsync(id);
            return RedirectToPage("/Lecons/EditLesson", new { id = lessonId });
        }
    }
}

Puroguramu.App/Pages/Lecons/LessonDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains.modelsDomains;
using Puroguramu.Domains.Repositories;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Puroguramu.Domains;

namespace Puroguramu.App.Pages.Lecons
{
    public class LessonDetail : PageModel
    {
        private readonly ILessonRepository _lessonRepository;
        private readonly IExoRepository _exoRepository;
        private readonly IStudentRepository _studentRepository;

        public LessonDetail(ILessonRepository lessonRepository, IExoRepository exoRepository, IStudentRepository studentRepository)
        {
            _lessonRepository = lessonRepository;
            _exoRepository = exoRepository;
            _studentRepository = studentRepository;
        }

        public LessonEditDto Lesson { get; set; }
        public List<StudentExerciseDto> Exercises { get; set; }
        public StudentDto Student { get; set; }

        public Exercice Exercice { get; set; }


        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            Student = await _studentRepository.GetStudentProfileAsync(User);

            Lesson = await _lessonRepository.GetLessonByIdAsync(id);
            if (Lesson == null)
            {
                return NotFound();
            }

            Exercises = await _lessonRepository.GetAllExercisesByLessonAsync(Student.Id, Lesson.Id);

            return Page();
        }
    }
}

Puroguramu.App/Pages/Lecons/CreateLesson.cshtml
@page
@model Puroguramu.App.Pages.Lecons.CreateLessonModel

@{
    Layout = "_Layout"; 
}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Créer une Leçon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-900 text-gray-200 flex flex-col min-h-screen">

    <!-- Main Content Area -->
    <main class="flex-grow container mx-auto p-10 mt-40"> <!-- Increased the margin-top here (mt-12) for more space -->
        <div class="max-w-md mx-auto bg-gray-800 p-8 rounded-xl shadow-lg">
            <h1 class="text-2xl font-bold text-center mb-6">Créer une Leçon</h1>
            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
            {
                <div class="bg-red-500 text-white p-4 rounded mb-4">
                    @Model.ErrorMessage
                </div>
            }
            <form method="post" class="space-y-6">
                @Html.AntiForgeryToken()
                <div>
                    <label for="title" class="block text-sm font-medium text-gray-300">Intitulé de la leçon</label>
                    <input type="text" id="title" name="Lesson.Title" required
                           minlength="5"
                           class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                           placeholder="Entrez un intitulé d'au moins 5 caractères">
                    <span asp-validation-for="Lesson.Title" class="text-red-500"></span>
                </div>
                <button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Créer la Leçon
                </button>
            </form>
        </div>
    </main>

</body>
</html>

Puroguramu.App/Pages/Lecons/EditLesson.cshtml
@page
@model Puroguramu.App.Pages.Lecons.EditLesson

@{
    Layout = "_Layout"; 
}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Éditer une Leçon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-900 text-gray-200 flex flex-col min-h-screen">

    <!-- Main Content Area -->
    <main class="flex-grow container mx-auto p-10 mt-20">
        <article class="max-w-4xl mx-auto bg-gray-800 p-8 rounded-2xl shadow-lg transition duration-300 ease-in-out hover:shadow-xl">
            <header>
                <h1 class="text-2xl font-bold text-center mb-6">Éditer la Leçon</h1>
            </header>
            
            <form method="POST" class="space-y-6">
                @Html.AntiForgeryToken()
                <input type="hidden" name="Lesson.Id" value="@Model.Lesson.Id">

                <section class="mb-6">
                    <label for="title" class="block text-lg font-semibold text-gray-300">Intitulé de la leçon</label>
                    <input type="text" id="title" name="Lesson.Title" required
                           class="mt-2 block w-full px-3 py-2 bg-gray-700 text-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 transition duration-300 ease-in-out border-none"
                           value="@Model.Lesson.Title">
                </section>

                <section>
                    <label for="description" class="block text-lg font-semibold text-gray-300">Description</label>
                    <textarea id="description" name="Lesson.Description" rows="3" required
                              class="mt-2 block w-full px-3 py-2 bg-gray-700 text-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 transition duration-300 ease-in-out border-none">@Model.Lesson.Description</textarea>
                </section>

                <section class="flex justify-center mt-10">
                    <button type="submit"
                            class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-lg shadow-md transition duration-300 ease-in-out">
                        Enregistrer les modifications
                    </button>
                </section>
            </form>


            <section>
                <div class="flex justify-end mb-4 mt-4">
                    <a href="~/Exercices/CreateExercice?lessonId=@Model.Lesson.Id"
                       class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-lg shadow-md transition duration-300 ease-in-out">
                        Ajouter un Exercice
                    </a>
                </div>
            </section>

            <section class="space-y-4">
                @foreach (var exercise in Model.Exercises.OrderBy(e => e.Order))
                {
                <div class="flex justify-between items-center bg-gray-700 p-4 rounded-lg shadow-md transition duration-300 ease-in-out hover:shadow-lg">
                    <header>
                        <h2 class="text-lg font-medium text-white">Exercice : @exercise.Title</h2>
                        <p class="text-gray-400">Statut : @(exercise.IsPublished ? "Publié" : "Non publié")</p>
                    </header>
                    <nav class="flex space-x-2">
                        <a href="~/Exercices/EditExercice?id=@exercise.Id&lessonId=@Model.Lesson.Id"
                           class="bg-blue-500 hover:bg-blue-600 text-white px-3 py-1 rounded-lg transition duration-300 ease-in-out">Éditer</a>

                        <form method="post" asp-page-handler="ToggleExercise" class="inline">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@exercise.Id"/>
                            <input type="hidden" name="lessonId" value="@Model.Lesson.Id"/>
                            <button type="submit"
                                    class="@(exercise.IsPublished ? "bg-purple-500 hover:bg-purple-600" : "bg-gray-500 hover:bg-gray-700") text-white px-3 py-1 rounded-lg transition duration-300 ease-in-out">
                                @((exercise.IsPublished ? "Masquer" : "Publier"))
                            </button>
                        </form>

                        <form method="post" asp-page-handler="DeleteExercise" class="inline">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@exercise.Id"/>
                            <input type="hidden" name="lessonId" value="@Model.Lesson.Id"/>
                            <button type="submit" class="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded-lg transition duration-300 ease-in-out">
                                Supprimer
                            </button>
                        </form>

                        <form method="post" asp-page-handler="ResetExercise" class="inline ml-4">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@exercise.Id"/>
                            <input type="hidden" name="lessonId" value="@Model.Lesson.Id"/>
                            <button type="submit"
                                    class="bg-yellow-500 hover:bg-yellow-600 text-white px-3 py-1 rounded-lg transition duration-300 ease-in-out">
                                Réinitialiser
                            </button>
                        </form>
                        
                        <form method="post" asp-page-handler="MoveExercise" class="inline">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@exercise.Id"/>
                            <input type="hidden" name="direction" value="up"/>
                            <input type="hidden" name="lessonId" value="@Model.Lesson.Id"/>
                            <button type="submit"
                                    class="bg-gray-500 hover:bg-gray-700 text-white px-3 py-1 rounded-lg transition duration-300 ease-in-out">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path fill-rule="evenodd"
                                          d="M10 18a1 1 0 001-1V5.414l3.293 3.293a1 1 0 001.414-1.414l-5-5a1 1 0 00-1.414 0l-5 5a1 1 0 101.414 1.414L9 5.414V17a1 1 0 001 1z"
                                          clip-rule="evenodd"/>
                                </svg>
                            </button>
                        </form>

                        <form method="post" asp-page-handler="MoveExercise" class="inline">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@exercise.Id"/>
                            <input type="hidden" name="direction" value="down"/>
                            <input type="hidden" name="lessonId" value="@Model.Lesson.Id"/>
                            <button type="submit"
                                    class="bg-gray-500 hover:bg-gray-700 text-white px-3 py-1 rounded-lg transition duration-300 ease-in-out">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path fill-rule="evenodd"
                                          d="M10 2a1 1 0 00-1 1v11.586l-3.293-3.293a1 1 0 10-1.414 1.414l5 5a1 1 0 001.414 0l5-5a1 1 0 00-1.414-1.414L11 14.586V3a1 1 0 00-1-1z"
                                          clip-rule="evenodd"/>
                                </svg>
                            </button>
                        </form>
                    </nav>
                </div>
                }
            </section>

           

            <footer>
                <!-- Validation Summary -->
                <div asp-validation-summary="ModelOnly" class="text-red-500 mt-6"></div>
            </footer>
        </article>
    </main>

</body>
</html>

Puroguramu.App/Pages/Lecons/LessonDetail.cshtml
@page
@model Puroguramu.App.Pages.Lecons.LessonDetail

@{
    Layout = "_Layout";
}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Détail de la Leçon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <script src="~/js/dropdown.js"></script>
</head>
<body class="bg-gray-900 text-gray-200 flex flex-col min-h-screen">

<div class="flex-grow container mx-auto p-10">
    <h1 class="text-3xl font-bold text-gray-100 mb-6">@Model.Lesson.Title</h1>
    <h2 class="text-xl text-gray-400 mb-4">@Model.Lesson.Description</h2>

    <!-- Inclusion de la vue partielle pour les exercices -->
    <partial name="Shared/_StudentExercisePartial" model="Model.Exercises"/>
</div>

</body>
</html>